function(oidn_download_wgpu out_dir)
  set(_ver v25.0.2.1)
  set(_url "https://github.com/gfx-rs/wgpu-native/releases/download/${_ver}/wgpu-linux-x86_64-release.zip")
  if(NOT EXISTS ${out_dir})
    file(MAKE_DIRECTORY ${out_dir})
  endif()
  set(_archive ${out_dir}/wgpu-native.zip)
  if(NOT EXISTS ${_archive})
    message(STATUS "Downloading wgpu-native ${_ver}")
    file(DOWNLOAD ${_url} ${_archive} SHOW_PROGRESS)
  endif()
  execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf ${_archive}
                  WORKING_DIRECTORY ${out_dir})
  set(OIDN_WGPU_DIR ${out_dir} CACHE INTERNAL "Path to downloaded wgpu-native")
endfunction()
